FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Target

Target project.

## Users Collection [/api/v1/users]
For GENDER attribute, possible values are: __'male'__, __'female'__ and __'other'__

### Sign Up [POST]

+ Request (application/json)
    + Body

            {
              "user":
                {
                  "username": "test",
                  "email": "test@test.com",
                  "name" : "Test",
                  "gender": "female",
                  "password": "password",
                  "password_confirmation": "password"
                }
            }


+ Response 200 (application/json)
    + Headers

            access-token: -abG_2b-LZMm_mJxz6dlGg
            client: SOn5zDcJF_pkmGvTF_5eMQ
            expiry: 1601058505
            uid: test@test.com


    + Body

            {
              "user": {
                "id": 1,
                "provider": "email",
                "uid": "test@test.com",
                "allow_password_change": false,
                "name": "Test",
                "email": "test@test.com",
                "created_at": "2018-09-25T18:28:25.716Z",
                "updated_at": "2018-09-25T18:28:25.834Z",
                "gender": "female"
              }
            }

+ Response 422

## Log In [/api/v1/users/sign_in]

### Log In [POST]

+ Request (application/json)

    + Body
            {
              "user":
                {
                  "email": "test@test.com",
                  "password": "password"
                }
            }


+ Response 200 (application/json)
    + Headers

            access-token: sO2bm_Bpdyoo8r78jZ-fqg
            client: QADgNCWRJj0LyRruqzYbBg
            expiry: 1489009792
            uid: test@test.com

    + Body

            {
              "user": {
                "id": 1,
                "provider": "email",
                "uid": "test@test.com",
                "allow_password_change": false,
                "name": "Test",
                "email": "test@test.com",
                "created_at": "2018-09-25T18:28:25.716Z",
                "updated_at": "2018-09-25T18:28:25.834Z",
                "gender": "female"
              }
            }

+ Response 401

## Log out [/api/v1/users/sign_out]

### Log out [DELETE]

+ Request (application/json)
    + Headers

            access-token: sO2bm_Bpdyoo8r78jZ-fqg
            client: QADgNCWRJj0LyRruqzYbBg
            expiry: 1489009792
            uid: test@test.com

+ Response 200 (application/json)
    + Body
            {
              "success": true
            }

+ Response 404
    + Body
            {
              "error": "User was not found or was not logged in."
            }

## Reset password [/api/v1/users/password]

https://github.com/lynndylanhurley/devise_token_auth/wiki/Reset-Password-Flow

### Reset password [POST]

Use this route to send a password reset confirmation email

+ Request (application/json)
    + Body

            {
              "email": "test@test.com",
              "redirect_url": "http://www.example.com"
            }

+ Response 200 (application/json)
    + Body

            {
              "success": true,
              "message": "An email has been sent to 'example@mail.com' containing instructions for resetting your password."
            }

### Reset password [PUT]

Use this route to change user's passwords

+ Request (application/json)
    + Headers

            access-token: -abG_2b-LZMm_mJxz6dlGg
            client: SOn5zDcJF_pkmGvTF_5eMQ
            uid: test@test.com

    + Body

            {
              "password": "12345678",
              "password_confirmation": "12345678"
            }

+ Response 200 (application/json)
    + Headers

            access-token: sO2bm_Bpdyoo8r78jZ-fqg
            client: QADgNCWRJj0LyRruqzYbBg
            expiry: 1489009792
            uid: test@test.com

    + Attributes (Profile Response)

## Edit reset password [/api/v1/users/password/edit]

### Edit reset password [GET]

This route is the destination URL for password reset confirmation

+ Request (application/json)
    + Parameters
        + reset_password_token (string, required)
        + redirect_url (string)

+ Response 200 (application/json)
    + Headers

            access-token: sO2bm_Bpdyoo8r78jZ-fqg
            client: QADgNCWRJj0LyRruqzYbBg
            expiry: 1489009792
            uid: test@test.com

## Topics Collection

### Get Topics

+ Request (application/json)
    + Headers
            access-token: 0JfjvKLv7NR3_d10350u2w
            client: pBx8B5nowYy3L-EXueP6nQ
            uid: test@test.com
            token-type: Bearer

+ Response 200 (application/json)
    + Body

            {
              "topics": 
                [
                  {
                      "id": 1,
                      "label": "Football"
                  }
                ]
            }

+ Response 401
    + Body
            {
              "error": "You need to sign in or sign up before continuing."
            }

## Profile Response (object)
+ id: 100 (number)
+ email: test@test.com (string)
+ provider: email (enum[string])
+ uid: test@test.com (string)
+ name: Test (string)
+ created_at: 2018-09-25T18:28:25.834Z (string)
+ updated_at": 2018-09-25T18:28:25.834Z (string)
+ "gender": "female" (string)

## Spot Collection

### Create Spot

+ Request (application/json)
    + Headers
            access-token: Aq0GCbYKWFA0oAbcvRzP9g
            client: 0WPgnm5Ns79vEqh1O81Akg
            uid: test@test.com
            token-type: Bearer

+ Response 200 (application/json)
    + Body

            {
                "spot": {
                    "id": 1,
                    "title": "spot",
                    "latitude": "-94.5566",
                    "longitude": "-94.5566",
                    "radius": "27384.4",
                    "topic_id": 1
                }
            }

+ Response 401
    + Body
            {
                "errors": [
                    "You need to sign in or sign up before continuing."
                ]
            }