json.id           user.id
json.provider     user.provider
json.uid          user.uid
json.name         user.name
json.email        user.email
json.gender       user.gender
json.created_at   user.created_at
json.updated_at   user.updated_at
json.avatar       user.avatar_url
json.push_token   user.push_token
